project:
  type: book

book:
  title: "Notes on developments of the EBS pollock assessment"
  author: "Jim Ianelli "
  date: "4/17/2023"
  chapters:
    - index.qmd
    - hoki.qmd
    - ling.qmd
    - summary.qmd
    - references.qmd
    - model.qmd

execute:
  echo: false
  warning: false
  message: false    

crossref:
  chapters: true
  title-delim: .     # (default is ":")
  ref-hyperlink: true # (default is true)

format:
  html:
    number-sections: false
    number-offset: 10
    number-depth: 3
  pdf:
    documentclass: scrreprt
    

engine: knitr
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in  

bibliography: references.bib




